apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: codecraftacr123.azurecr.io/taskapi:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
